### ISSUE TITLE
Better FIDO2 encoding

### ISSUE THREAD

**Issue by xi** [xi/django-mfa3#1]
The data that needs to be passed between client and server for FIDO2 are nested structures containing binary strings. The go to encoding for nested data would be JSON, but JSON does not support binary strings. Inspired by the [python-fido2 example](https://github.com/Yubico/python-fido2/blob/master/examples/server/server.py) I therefore used [CBOR](https://datatracker.ietf.org/doc/html/rfc7049) instead. This has two issues though:

- While the browser does use CBOR internally, it is not exposed to JavaScript. So a separate library is needed.
- The result of CBOR encoding is a flat binary string. This is still hard to pass to JavaScript. I used a JSON-encoded integer list, which is grossly inefficient in terms of space.

I am not sure why the FIDO2 authors chose to use structures that cannot easily be passed to the client.

Unfortunately the JavaScript runtime does not have [proper base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64#solution_2_%E2%80%93_rewriting_atob_and_btoa_using_typedarrays_and_utf-8) support either, so there are very few building blocks for handling binary data.

I currently think the best bet is to use JSON with binary strings converted to lists of integers. Whether a specific value should be converted to binary could be hard coded, as the data structures that are used in FIDO2 are known.

**Comment by rugk** [comment]
I guess you know/saw https://webauthn.io/ / https://webauthn.guide/, and they also use CBOR there, so if you trust them (if I read it correctly it's basically Google :upside_down_face:), this is a good choice.

**Comment by xi** [comment]
There is some movement on this. The latest [editor's draft of the spec](https://w3c.github.io/webauthn/#sctn-parseCreationOptionsFromJSON) containes functions to serialize the structures to JSON with base64url for the binary parts. python-fido2 1.1.0 has already added support for that.

However, as long as this is not available in browsers I do not see a convincing reason to use this because we would just replace one dependency (cbor.js) by another one (webauthn-json.browser-ponyfill.js).
