### ISSUE TITLE
Test issuing warning models.W042

### ISSUE THREAD

**Issue by hleroy** [xi/django-mfa3#16]
My test runner is issuing a warning regarding the change introduced in Django 3.2
`(models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'`

It's not big deal, but would you consider setting the default auto field at app or model level?
See [this post](https://dev.to/weplayinternet/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-518n)

**Comment by xi** [comment]
My idea here was to do whatever people have configured in their settings via `DEFAULT_AUTO_FIELD`. This is set to `"django.db.models.BigAutoField"` by default for new projects.

If we set this on the app/model level, we would force a migration on one half of existing users. I don't really see why that is necessary. So I would rather keep it as it is.

Does this make sense to you?

**Comment by hleroy** [comment]
Yep, understood.
